name: 'Azure SDK GitHub Event Handler'
description: 'Handle GitHub event'
inputs:
  token:
    description: "GitHub Event Token"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        cd $GITHUB_ACTION_PATH
        cat > ./github_payload.json << 'EOF'
        ${{ toJson(github.event) }}
        EOF
        go run . ./github_payload.json
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
