name: 'Azure SDK GitHub Event Handler'
description: 'Handle GitHub event'
inputs:
  token:
    description: "GitHub Event Token"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        cd $GITHUB_ACTION_PATH
        go run . ${{ github.event_path }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}

    - name: Archive github event data
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: event
        path: ${{ github.event_path }}
