name: 'Azure SDK GitHub Event Handler'
description: 'Handle GitHub event'
inputs:
  token:
    description: "GitHub Event Token"
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        cd $GITHUB_ACTION_PATH
        echo "$GITHUB_PAYLOAD" > ./github_payload.json
        go run . ./github_payload.json
      shell: bash
      env:
        GITHUB_PAYLOAD: ${{ toJson(github.event) }}
        GITHUB_TOKEN: ${{ inputs.token }}
